---
name: Commenting bot to report CI failures and suggest fixes
description: |
  This action is used to comment on a pull request with the CI failure details
  and suggest fixes to the user. It checks if the comment is already present and
  updates the comment with the latest CI failure details.

inputs:
  issue-number:
    description: The pull request number
    required: true
  ci_name:
    description: The name of the CI
    required: true
  step_name:
    description: The name of the step
    required: true
  commit_id:
    description: The commit id to use
    required: true
  message:
    description: The error message to use
    required: true
  username:
    description: The username to tag in the message
    default: jaeaeich
    required: false
  error-after-comment:
    description: Stop the workflow after commenting
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Create the title of the comment
      id: globals
      shell: bash
      run: |
        echo "TITLE=Hey @${{ inputs.username }}, `${{ inputs.ci_name}}` failed at `${{ inputs.step_name }}`!" >> "${GITHUB_OUTPUT}"
  
    - name: Find if comment is already present
      uses: peter-evans/find-comment@v3
      id: find-comment
      with:
        issue-number: ${{ inputs.issue-number }}
        comment-author: 'github-actions[bot]'
        body-includes: ${{ steps.globals.outputs.TITLE }}

    - name: Fill in the template
      if: steps.find-comment.outputs.comment-id == ''
      id: fresh-comment
      uses: peter-evans/create-or-update-comment
      with:
        issue-number: ${{ inputs.issue-number }}
        body: |
          ${{ steps.globals.outputs.TITLE }}
          ${{ inputs.message }}

    - name: Comment with the updated template
      if: steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ inputs.issue-number }}
        body: |
          Hey @${{ inputs.username }}, it failed again for commit `${{ inputs.commit_id }}`!
    
    - name: Fail the workflow if error-after-comment is true
      if: steps.find-comment.outputs.comment-id != '' && ${{ inputs.error-after-comment }}
      shell: bash
      run: exit 1
...